"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const auth_1 = require("../middleware/auth");
const requireAdmin_1 = require("../middleware/requireAdmin");
const router = (0, express_1.Router)();
router.post("/register", auth_controller_1.registerUser);
router.post("/login", auth_controller_1.loginUser);
router.post("/logout", auth_1.requireAuth, auth_controller_1.logoutUser);
router.get("/me", auth_1.requireAuth, auth_controller_1.getCurrentUser);
router.post("/forgot-password", auth_controller_1.forgotPasswordRequest);
router.post("/reset-password/:resetToken", auth_controller_1.resetForgottenPassword);
router.post("/change-password", auth_1.requireAuth, auth_controller_1.changeCurrentPassword);
router.post("/refresh", auth_controller_1.refreshAccessToken);
// Admin-only routes
router.get("/all", auth_1.requireAuth, requireAdmin_1.requireAdmin, auth_controller_1.getAllUsers);
router.post("/:userId", auth_1.requireAuth, requireAdmin_1.requireAdmin, auth_controller_1.assignRole);
router.delete("/:userId", auth_1.requireAuth, requireAdmin_1.requireAdmin, auth_controller_1.deleteUser);
exports.default = router;
